### ISSUE TITLE
`include` and `include_list` function differently for `ses` folders

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3598]
Context here: https://forum.spinalcordmri.org/t/sct-run-batch-include-list/770/3?u=joshuacwnewton

> I have tried your solution:
>
> ```
> ("include_list" : ["sub-0001", "sub-0002"]) 
> ```
> 
> but it didn't work. Since our dataset is longitudinal (organised in this way: sub-0001/ses-01/anat, …) I then tried to include also ses into the list:
> 
> ```
> "include_list" : ["sub-0001/ses-01","sub-0002/ses-01"]
> ```
> 
> In this configuration, it works. So, it seems that include_list required ses for longitudinal studies. 
> 
> On the other hand, `include` accepts both variants (with ses:  `"include" : "sub-0001/ses-01"` and also without ses:  `"include" : "sub-0001"`)

So, for datasets organized with `ses` folders, it seems that you can't just specify `include_list: sub-0001` -- you have to specify the `ses` part of the path, too.

**Comment by joshuacwnewton** [comment]
I created a multi-subject, multi-session test dataset here (with image files removed, as they're not necessary for debugging this issue): [test_dataset.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/9351589/test_dataset.zip)
 
I then ran the following command:

```
sct_run_batch -config config.yml -script process_data.sh
```

---

It seems like the problem here is pretty straightforward:

* Individual `ses` subfolders are treated as unique "subject directories" by SCT's parsing code:

    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/41c0ef74a1d78d59fce18f6ee41c251af4b027aa/spinalcordtoolbox/scripts/sct_run_batch.py#L444-L447

   ![image](https://user-images.githubusercontent.com/16181459/184895090-4952a559-51c6-4853-b8f7-e1fe5b6142e5.png)

* `-include-list` does exact matching (so `sub-01` does not match `sub-01/ses-01`:

    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/41c0ef74a1d78d59fce18f6ee41c251af4b027aa/spinalcordtoolbox/scripts/sct_run_batch.py#L458

* `-include`, on the other hand, does pattern matching (so `sub-01` *does* match `sub-01/ses-01`:

    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/41c0ef74a1d78d59fce18f6ee41c251af4b027aa/spinalcordtoolbox/scripts/sct_run_batch.py#L454

**Comment by joshuacwnewton** [comment]
One solution we could consider would be to check against the individual path entities ("sub-01", "ses-01") in addition to the full path ("sub-01/ses-01").

That way, `include-list` could support the following combinations:

```yml
# 1. Specifying precise subject/session combinations
include_list: ["sub-01/ses-02", "sub-05/ses-01"] 

# 2. Specifying individual sessions (across all subjects)
include_list: ["ses-01", "ses-02", "ses-04"] 

# 3. Specifying individual subjects (across all sessions)
include_list: ["sub-01", "sub-03"] 
```

Right now, `-include-list` only supports 1.
