### ISSUE TITLE
Extremely long installation times on Linux

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3758]
### Description

As of 6b8613a10caa95d35e015ab35ca6e368ef067894, installing SCT on Linux takes over an hour. macOS is unaffected.

### Steps to Reproduce

Run this Github workflow: https://github.com/shimming-toolbox/shimming-toolbox/actions/runs/2105233360/workflow#L55-L62

```
jobs:
  test:
    env:
      FSLOUTPUTTYPE: NIFTI_GZ
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'macos-10.15'
          # - 'macos-11.0'
          - 'ubuntu-18.04'
          - 'ubuntu-20.04'
 
# [  .....  ]

      - name: Spinal Cord Toolbox clone
        run: |
          cd ~/work
          git clone --depth 1 https://github.com/neuropoly/spinalcordtoolbox
          cd spinalcordtoolbox
          # Use HEAD commit hash as key for cache
          git rev-parse HEAD > $GITHUB_WORKSPACE/.sct_HEAD_hash
          cat $GITHUB_WORKSPACE/.sct_HEAD_hash
```

**Expected behavior:** SCT should install in a reasonable amount of time, ideally under 10 minutes.

**Actual behavior:**

Seen at https://github.com/shimming-toolbox/shimming-toolbox/runs/5951273471?check_suite_focus=true:

![Screenshot 2022-04-08 at 22-18-13 Share a single conda environment  · shimming-toolbox_shimming-toolbox@f53d61a](https://user-images.githubusercontent.com/987487/162552993-fcce018e-26de-4a6b-b9f2-d6fed84a058d.png)

It said something about "Building wheel for ITKSimple", but then I reloaded the page and lost the output. If it ever does actually finish I can get a more accurate log for you.

This did *not* happen just a couple days ago, in https://github.com/shimming-toolbox/shimming-toolbox/runs/5858854655?check_suite_focus=true:

![Screenshot 2022-04-08 at 22-20-48 Share a single conda environment  · shimming-toolbox_shimming-toolbox@a068b21](https://user-images.githubusercontent.com/987487/162553046-683e3bc5-cfdb-4198-af0b-5d63cd1aaef9.png)

Did one of our dependencies release a new version that no longer has .whls that work on Ubuntu 18.04?
